server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: "016619"
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  type-aliases-package: com.zua.pojo,com.zua.vo
  mapper-locations: classpath*:com/zua/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty

logging:
  pattern:
    console:  '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

#jwt配置
jwt:
  secret: com.zua
  #30分钟过期
  expiration: 1800000